# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Child_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(639, 457)
        font = QtGui.QFont()
        font.setPointSize(18)
        Form.setFont(font)
        Form.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(225, 225, 225);\n"
"border:2px groove gray;\n"
"border-radius:10px;\n"
"padding:2px 4px;\n"
"border-style: outset;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color:rgb(229, 241, 251);\n"
"color: black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color:rgb(0, 0, 0);\n"
"border-style: inset;\n"
"}")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(120, 70, 361, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(120, 370, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setIconSize(QtCore.QSize(18, 18))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 370, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Child_UI"))
        self.pushButton.setText(_translate("Form", "openFile"))
        self.pushButton_2.setText(_translate("Form", "Back"))
