# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stats1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import picture_rc

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(902, 550)
        Form.setStyleSheet("background-image: url(\"D:\\Pycharm\\Qt-Camera\\Qt-Camera\\BackgroundPic.jpg\")")
        self.openCamera = QtWidgets.QPushButton(Form)
        self.openCamera.setGeometry(QtCore.QRect(30, 447, 141, 51))
        self.openCamera.setObjectName("openCamera")
        self.capturePic = QtWidgets.QPushButton(Form)
        self.capturePic.setGeometry(QtCore.QRect(250, 450, 131, 51))
        self.capturePic.setObjectName("capturePic")
        self.calculateWood = QtWidgets.QPushButton(Form)
        self.calculateWood.setGeometry(QtCore.QRect(460, 450, 121, 51))
        self.calculateWood.setObjectName("calculateWood")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 50, 300, 300))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(410, 50, 300, 300))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(40, 390, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(154, 390, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 390, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(387, 391, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(617, 391, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(501, 391, 93, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(727, 391, 111, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(660, 450, 131, 51))
        self.pushButton_8.setObjectName("pushButton_8")
        self.listView = QtWidgets.QListView(Form)
        self.listView.setGeometry(QtCore.QRect(-5, 0, 911, 551))
        self.listView.setStyleSheet("background-image: url(:/BackgroundPic.jpg);")
        self.listView.setObjectName("listView")
        self.listView.raise_()
        self.openCamera.raise_()
        self.capturePic.raise_()
        self.calculateWood.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.openCamera.setText(_translate("Form", "拍照"))
        self.capturePic.setText(_translate("Form", "重置"))
        self.calculateWood.setText(_translate("Form", "关闭摄像头"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.pushButton.setText(_translate("Form", "亮度"))
        self.pushButton_2.setText(_translate("Form", "对比度"))
        self.pushButton_3.setText(_translate("Form", "色调"))
        self.pushButton_4.setText(_translate("Form", "饱和度"))
        self.pushButton_5.setText(_translate("Form", "曝光时间"))
        self.pushButton_6.setText(_translate("Form", "锐度"))
        self.pushButton_7.setText(_translate("Form", "白平衡和温度"))
        self.pushButton_8.setText(_translate("Form", "材积计算"))

