# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Camera.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1199, 721)
        MainWindow.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(225, 225, 225);\n"
"border:2px groove gray;\n"
"border-radius:10px;\n"
"padding:2px 4px;\n"
"border-style: outset;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color:rgb(229, 241, 251);\n"
"color: black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color:rgb(0, 0, 0);\n"
"border-style: inset;\n"
"}\n"
"QMenu{\n"
"   background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #00ffff, stop:0.5 #505050, stop:0.98 #00ffff);\n"
"   border:0px;\n"
"   border-radius:4px;\n"
"   color:white;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 555, 1141, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/jsjt0/.designer/backup/pic/pai.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/jsjt0/.designer/backup/pic/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/jsjt0/.designer/backup/pic/Hint.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_4.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/jsjt0/.designer/backup/pic/g1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 40, 1091, 481))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(500, 500))
        self.label.setStyleSheet("border-image: url(:/newPrefix/pic/g1.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(500, 500))
        self.label_2.setStyleSheet("border-image: url(:/newPrefix/pic/wallhaven-rd9q77.jpg);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 630, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(630, 630, 151, 31))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1199, 36))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuBar.sizePolicy().hasHeightForWidth())
        self.menuBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menuBar.setFont(font)
        self.menuBar.setStyleSheet("QMenuBar{\n"
"   background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #00ffff, stop:0.5 #505050, stop:0.98 #00ffff);\n"
"   border:0px;\n"
"   border-radius:4px;\n"
"   color:white;\n"
"}")
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menu.setFont(font)
        self.menu.setStyleSheet("")
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.actionliangdu = QtWidgets.QAction(MainWindow)
        self.actionliangdu.setObjectName("actionliangdu")
        self.action_10 = QtWidgets.QAction(MainWindow)
        self.action_10.setObjectName("action_10")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.action_11 = QtWidgets.QAction(MainWindow)
        self.action_11.setObjectName("action_11")
        self.action_19 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.action_19.setFont(font)
        self.action_19.setObjectName("action_19")
        self.action_20 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.action_20.setFont(font)
        self.action_20.setObjectName("action_20")
        self.action_21 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.action_21.setFont(font)
        self.action_21.setObjectName("action_21")
        self.action_22 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.action_22.setFont(font)
        self.action_22.setObjectName("action_22")
        self.action_23 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.action_23.setFont(font)
        self.action_23.setObjectName("action_23")
        self.action_24 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.action_24.setFont(font)
        self.action_24.setObjectName("action_24")
        self.action_25 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.action_25.setFont(font)
        self.action_25.setObjectName("action_25")
        self.menu.addAction(self.action_19)
        self.menu.addAction(self.action_20)
        self.menu.addAction(self.action_21)
        self.menu.addAction(self.action_22)
        self.menu.addAction(self.action_23)
        self.menu.addAction(self.action_24)
        self.menu.addAction(self.action_25)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图像采集"))
        self.pushButton.setText(_translate("MainWindow", "拍照"))
        self.pushButton_2.setText(_translate("MainWindow", "重置"))
        self.pushButton_3.setText(_translate("MainWindow", "关闭"))
        self.pushButton_4.setText(_translate("MainWindow", "材积计算"))
        self.label_3.setText(_translate("MainWindow", "请输入检尺长度："))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "检尺长"))
        self.menu.setTitle(_translate("MainWindow", "参数调整"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.actionliangdu.setText(_translate("MainWindow", "liangdu"))
        self.action_10.setText(_translate("MainWindow", "亮度"))
        self.action_3.setText(_translate("MainWindow", "对比度"))
        self.action_4.setText(_translate("MainWindow", "色调"))
        self.action_5.setText(_translate("MainWindow", "饱和度"))
        self.action_6.setText(_translate("MainWindow", "锐度"))
        self.action_7.setText(_translate("MainWindow", "曝光时间"))
        self.action_8.setText(_translate("MainWindow", "白平衡和温度"))
        self.action_11.setText(_translate("MainWindow", "亮度"))
        self.action_19.setText(_translate("MainWindow", "亮度"))
        self.action_20.setText(_translate("MainWindow", "对比度"))
        self.action_21.setText(_translate("MainWindow", "色调"))
        self.action_22.setText(_translate("MainWindow", "饱和度"))
        self.action_23.setText(_translate("MainWindow", "锐度"))
        self.action_24.setText(_translate("MainWindow", "曝光时间"))
        self.action_25.setText(_translate("MainWindow", "白平衡和温度"))
import icon_rc
import picture_rc
